name: moodJournal

settings:
  DEVELOPMENT_TEAM: 9HYXUXTGF6

packages:
  WrappingHStack:
    url: https://github.com/ksemianov/WrappingHStack
    version: 0.2.0
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    version: 16.1.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 5.9.1

targets:
  MoodJournal:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 17.0
    sources:
      - path: MoodJournal
        exclude: [Info.plist]
    dependencies:
      - package: SocketIO
        product: SocketIO
      - package: WrappingHStack
        product: WrappingHStack
      - package: Alamofire
        product: Alamofire
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_NAME: MoodJournal
      PRODUCT_BUNDLE_IDENTIFIER: com.isabellagessl.MoodJournal
      INFOPLIST_FILE: MoodJournal/Info.plist
    entitlements:
      path: MoodJournal/MoodJournal.entitlements
      properties:
        aps-environment: development
